name: Taha Raja
favicon: null
layout_spectrum: 0.1294387101661414
typography_spectrum: 0.6235472897533327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#617498'
    - '#c4c8ce'
    - '#44361f'
    - '#010101'
    - '#b9a181'
  brandStrength: 0.3744745112489909
  lightness: 0.7924820072948933
  saturation: 0.5258774405810982
  rhythmicContrast: 0.5395818129181862
purpose: []
